// <auto-generated />
namespace MattAndMere.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addEmailToRes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addEmailToRes));
        
        string IMigrationMetadata.Id
        {
            get { return "201707141505457_addEmailToRes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
